### PR TITLE
Add available ssh identities when starting ssh-agent

### PR DESCRIPTION
**Pull request by ctuffli**

### CODE REVIEW

**Comment by kmoore134** [comment]
Looks good, thanks!

**Comment by ctuffli** [comment]
@kmoore134 , just updated to the latest TrueOS and see this change in
```/usr/local/share/trueos/desktop-defaults/usr/local/share/trueos/xstartup/ssh-agent.sh``` but not ```/usr/local/share/trueos/xstartup/ssh-agent.sh```. Is that expected? Was there another part of this that I should have fixed as well?

**Comment by kmoore134** [comment]
Files in that dir are only updated at installation. I've moved them now so they get updated by package upgrades as well :) 

https://github.com/trueos/trueos-core/commit/00ee20181e37070db614a2b07a298866e8da7655

**Comment by ctuffli** [comment]
Thanks!

**Pull request merged**
